FROM php:7.4-apache

RUN curl -o /usr/local/share/ca-certificates/NTUT_CA.crt https://raw.githubusercontent.com/JoeyChen-NTUT/php-7.3-apache/master/NTUT_Computer_And_Network_Center_Root_CA.crt
RUN update-ca-certificates --fresh

RUN export DEBIAN_FRONTEND=noninteractive
RUN apt clean
RUN apt update
RUN apt install -y apt-utils
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

#modify php.ini for env require
RUN cp /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini
RUN sed -i -e 's/max_execution_time = 30/max_execution_time = 300/g' /usr/local/etc/php/php.ini && \
    sed -i -e 's/upload_max_filesize = 2M/upload_max_filesize = 4G/g' /usr/local/etc/php/php.ini && \
    sed -i -e 's/post_max_size = 8M/post_max_size = 10G/g' /usr/local/etc/php/php.ini && \
    sed -i -e 's/memory_limit = 128M/memory_limit = 1024M/g' /usr/local/etc/php/php.ini && \
    sed -i -e 's/;date.timezone =/date.timezone = Asia\/Taipei/g' /usr/local/etc/php/php.ini && \
    sed -i -e 's/max_file_uploads = 20/max_file_uploads = 300/g' /usr/local/etc/php/php.ini && \
    sed -i -e 's/max_input_time = 60/max_input_time = 120/g' /usr/local/etc/php/php.ini

#install mysqli extensions
RUN docker-php-ext-install pdo pdo_mysql sockets && docker-php-ext-enable pdo pdo_mysql sockets

#install odbc and informix
RUN apt-get install unixodbc unixodbc-dev libncurses5 -y

COPY csdk.tar.partaa /tmp/csdk.tar.partaa
COPY csdk.tar.partab /tmp/csdk.tar.partab
COPY csdk.tar.partac /tmp/csdk.tar.partac
COPY csdk.tar.partad /tmp/csdk.tar.partad
COPY csdk.tar.partae /tmp/csdk.tar.partae
COPY csdk.tar.partaf /tmp/csdk.tar.partaf
COPY csdk.tar.partag /tmp/csdk.tar.partag
COPY csdk.tar.partah /tmp/csdk.tar.partah

RUN cat /tmp/csdk.tar.parta* > /tmp/csdk.tar && \
    mkdir /tmp/csdk && \
    tar -xvf /tmp/csdk.tar -C /tmp/csdk
    
RUN cd /tmp/csdk && \
    ./installclientsdk -i silent -DLICENSE_ACCEPTED=TRUE

RUN echo 'export INFORMIXDIR="/opt/IBM/Informix_Client-SDK"' >> /root/.bashrc
RUN echo 'export LD_LIBRARY_PATH="$INFORMIXDIR/lib:$INFORMIXDIR/lib/esql:$INFORMIXDIR/cli:$LD_LIBRARY_PATH"' >> /root/.bashrc
RUN echo 'export SHLIB_PATH="$INFORMIXDIR/lib/esql"' >> /root/.bashrc
RUN echo 'export LIBPATH="$INFORMIXDIR/lib/esql"' >> /root/.bashrc
RUN echo 'export ODBCINI="/etc/odbc.ini"' >> /root/.bashrc
RUN echo 'export ODBCSYSINI="/etc"' >> /root/.bashrc

RUN docker-php-ext-configure pdo_odbc --with-pdo-odbc=unixODBC,/usr \
 && docker-php-ext-install pdo_odbc


#enable mods
RUN a2enmod rewrite
